<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<AssemblyName>HomewardBound</AssemblyName>
		<RootNamespace>HomewardBound</RootNamespace>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="Assembly-CSharp">
			<HintPath>..\Assembly-CSharp.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="com.rlabrecque.steamworks.net">
		  <HintPath>..\com.rlabrecque.steamworks.net.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\UnityEngine.CoreModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

</Project>